export const buttonLabels = Object.freeze({
  cancelDelete: 'No',
  clearSelection: 'Clear selection',
  close: 'Close',
  confirmDelete: 'Yes',
  follow: 'Follow',
  guestLogin: 'Guest Log In',
  loadMoreFollowers: 'Load more followers',
  loadMoreFollowing: 'Load more following',
  loadMorePosts: 'Load more posts',
  loadingFollowers: 'Loading followers...',
  loadingFollowing: 'Loading following...',
  loadingPosts: 'Loading posts...',
  logIn: 'Log In',
  loggingOut: 'Logging out…',
  logOut: 'Log Out',
  post: 'Post',
  resendVerificationEmail: 'Resend verification email',
  retry: 'Try again',
  resendingVerificationEmail: 'Sending verification email…',
  resetPassword: 'Reset password',
  resettingPassword: 'Resetting password…',
  sendResetLink: 'Send reset link',
  sendingResetLink: 'Sending reset link…',
  save: 'Save',
  signUp: 'Sign Up',
  unfollow: 'Unfollow',
  updateAvatar: 'Update avatar',
  updateEmail: 'Update email',
  updatePassword: 'Update password',
  updatingAvatar: 'Updating avatar…',
  updatingEmail: 'Updating email…',
  updatingPassword: 'Updating password…'
});

export const buttonActionLabels = Object.freeze({
  deletePost: postLabel => `Delete ${postLabel}`,
  editPost: postLabel => `Edit ${postLabel}`,
  followUser: username => `${buttonLabels.follow} ${username}`,
  likePost: postLabel => `Like ${postLabel}`,
  unfollowUser: username => `${buttonLabels.unfollow} ${username}`,
  unlikePost: postLabel => `Unlike ${postLabel}`
});
